import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

export const BOOKMARK_OUTPUT_PATH = 'output/developer-learning-bookmarks.html';
const ROOT_TITLE = 'Microsoft Student Accelerator';

export interface LearningLink {
  title: string;
  url: string;
  description: string;
}

export interface LinkInput extends LearningLink {
  category: string;
}

export interface StoredLink extends LearningLink {
  category: string;
}

const escapeHtml = (value: string): string => value
  .replaceAll('&', '&amp;')
  .replaceAll('<', '&lt;')
  .replaceAll('>', '&gt;')
  .replaceAll('"', '&quot;')
  .replaceAll("'", '&#39;');

const canonicalizeUrl = (value: string): string => {
  const url = new URL(value);
  url.hash = '';
  return url.toString();
};

export const validateLink = (link: LinkInput): StoredLink => {
  const title = link.title.trim();
  const category = link.category.trim();
  const description = link.description.trim();

  if (!title || title.length > 200) throw new Error('Link title must be between 1 and 200 characters.');
  if (!category || category.length > 100 || category.includes('>')) throw new Error('Category must be between 1 and 100 characters and cannot contain >.');
  if (description.length > 500) throw new Error('Link description cannot exceed 500 characters.');

  let url: string;
  try {
    url = canonicalizeUrl(link.url.trim());
  } catch {
    throw new Error('Link URL must be valid.');
  }
  if (!url.startsWith('https://')) throw new Error('Link URL must use HTTPS.');

  return { title, url, description, category };
};

const emptyDocument = (): string => `<!DOCTYPE NETSCAPE-Bookmark-file-1>\n<!-- Generated by developer-workbench-mcp. -->\n<TITLE>${ROOT_TITLE}</TITLE>\n<H1>${ROOT_TITLE}</H1>\n<DL><p>\n  <DT><H3>${ROOT_TITLE}</H3>\n  <DL><p>\n    <DT><H3>Developer Learning</H3>\n    <DL><p>\n    </DL><p>\n  </DL><p>\n</DL><p>\n`;

const folderBlock = (category: string, links: LearningLink[]): string => {
  const renderedLinks = links.map((link) => `      <DT><A HREF="${escapeHtml(link.url)}" ADD_DATE="0">${escapeHtml(link.title)}</A>${link.description ? `<!-- ${escapeHtml(link.description)} -->` : ''}`).join('\n');
  return `    <DT><H3>${escapeHtml(category)}</H3>\n    <DL><p>\n${renderedLinks}\n    </DL><p>`;
};

export const renderBookmarks = (links: StoredLink[]): string => {
  const categories = new Map<string, LearningLink[]>();
  for (const link of links) {
    const categoryLinks = categories.get(link.category) ?? [];
    categoryLinks.push(link);
    categories.set(link.category, categoryLinks);
  }
  const folders = [...categories.entries()].sort(([left], [right]) => left.localeCompare(right)).map(([category, categoryLinks]) => folderBlock(category, categoryLinks)).join('\n');
  return emptyDocument().replace('    </DL><p>', `${folders}\n    </DL><p>`);
};

export const readLinks = async (filePath: string): Promise<StoredLink[]> => {
  let document: string;
  try {
    document = await readFile(filePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }

  const links: StoredLink[] = [];
  const linkPattern = /<DT><A HREF="([^"]+)"[^>]*>([^<]*)<\/A>(?:<!-- ([\s\S]*?) -->)?/gi;
  let match: RegExpExecArray | null;
  while ((match = linkPattern.exec(document)) !== null) {
    const url = match[1];
    const title = match[2];
    if (!url || !title) continue;
    const beforeLink = document.slice(0, match.index);
    const categoryMatches = [...beforeLink.matchAll(/<DT><H3>([^<]+)<\/H3>/gi)];
    const category = categoryMatches.at(-1)?.[1];
    if (category && category !== ROOT_TITLE && category !== 'Developer Learning') {
      links.push({ category, title, url, description: match[3] ?? '' });
    }
  }
  return links;
};

export const addLinks = async (filePath: string, newLinks: LinkInput[]): Promise<{ added: StoredLink[]; skipped: StoredLink[] }> => {
  const validated = newLinks.map(validateLink);
  const existing = await readLinks(filePath);
  const knownUrls = new Set(existing.map((link) => canonicalizeUrl(link.url)));
  const added: StoredLink[] = [];
  const skipped: StoredLink[] = [];
  for (const link of validated) {
    if (knownUrls.has(link.url) || added.some((item) => item.url === link.url)) skipped.push(link);
    else {
      added.push(link);
      knownUrls.add(link.url);
    }
  }
  if (added.length === 0) return { added, skipped };

  await mkdir(dirname(filePath), { recursive: true });
  const temporaryPath = `${filePath}.${process.pid}.tmp`;
  await writeFile(temporaryPath, renderBookmarks([...existing, ...added]), 'utf8');
  await rename(temporaryPath, filePath);
  return { added, skipped };
};

export const getOutputPath = (workingDirectory: string): string => `${workingDirectory}/${BOOKMARK_OUTPUT_PATH}`;
